const crypto = require('crypto');
const { MongoClient } = require('mongodb');
const { MENU_VERSION } = require('./menu-catalog');
const { loadMenuFromFolder, getMenuCategories } = require('./load-menu');

let client;
let database;
let readyPromise;

function hasMongoEnv() { return Boolean(process.env.MONGODB_URI); }
function describeMongoEnv() { return { mode: 'mongodb', hasMongoUri: hasMongoEnv(), database: process.env.MONGODB_DB || 'delight_cafe', hasSessionSecret: Boolean(process.env.SESSION_SECRET) }; }
function formatMongoError(err) { return err?.code === 'MONGODB_URI_MISSING' ? err.message : `MongoDB connection failed: ${err?.message || 'unknown error'}`; }
function collection(name) { if (!database) throw new Error('MongoDB is not initialized'); return database.collection(name); }
async function nextId(name) {
  const result = await collection('counters').findOneAndUpdate({ _id: name }, { $inc: { value: 1 } }, { upsert: true, returnDocument: 'after' });
  return Number(result.value?.value || 1);
}

function normalizeAuthEmail(value) { const email = String(value || '').trim().toLowerCase(); if (!email) return ''; return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) ? email : null; }
function normalizeAuthPhone(value) { let digits = String(value || '').replace(/\D/g, ''); if (!digits) return ''; if (digits.length === 12 && digits.startsWith('91')) digits = digits.slice(2); else if (digits.length === 11 && digits.startsWith('0')) digits = digits.slice(1); else if (digits.length > 10) digits = digits.slice(-10); return /^\d{10}$/.test(digits) ? digits : null; }
function normalizeAuthIdentifier(raw) { const value = String(raw || '').trim(); if (!value) return { kind: 'empty', value: '' }; if (value.includes('@')) { const email = normalizeAuthEmail(value); return email === null ? { kind: 'invalid_email', value: '' } : { kind: 'email', value: email }; } if (value.replace(/\D/g, '').length >= 10) { const phone = normalizeAuthPhone(value); return phone === null ? { kind: 'invalid_phone', value: '' } : { kind: 'phone', value: phone }; } return { kind: 'username', value: value.toLowerCase() }; }

async function initMongo() {
  if (readyPromise) return readyPromise;
  readyPromise = (async () => {
    if (!hasMongoEnv()) { const error = new Error('MONGODB_URI is required. Set MONGODB_URI and redeploy.'); error.code = 'MONGODB_URI_MISSING'; throw error; }
    client = new MongoClient(process.env.MONGODB_URI, { serverSelectionTimeoutMS: 10000 });
    await client.connect();
    database = client.db(process.env.MONGODB_DB || undefined);
    await Promise.all([
      collection('users').createIndex({ usernameLower: 1 }, { unique: true }),
      collection('users').createIndex({ email: 1 }, { unique: true, sparse: true }),
      collection('users').createIndex({ phone: 1 }, { unique: true, sparse: true }),
      collection('menu_items').createIndex({ name: 1 }, { unique: true }),
      collection('orders').createIndex({ userId: 1 }),
      collection('orders').createIndex({ invoiceToken: 1 }, { unique: true, sparse: true }),
      collection('sessions').createIndex({ expired: 1 }, { expireAfterSeconds: 0 }),
      collection('app_meta').createIndex({ key: 1 }, { unique: true })
    ]);
    await seedUsers();
    await syncMenuCatalog();
    await cleanupExpiredSessions();
    return { engine: 'mongodb' };
  })().catch((error) => { readyPromise = null; database = null; if (client) client.close().catch(() => {}); client = null; throw error; });
  return readyPromise;
}

async function seedUsers() { if (await collection('users').countDocuments()) return; await collection('users').insertMany([{ id: await nextId('users'), username: 'admin', usernameLower: 'admin', password: 'admin123', role: 'admin', email: null, phone: null, createdAt: new Date().toISOString() }, { id: await nextId('users'), username: 'user', usernameLower: 'user', password: 'password', role: 'user', email: null, phone: null, createdAt: new Date().toISOString() }]); }
async function syncMenuCatalog() { const stored = await getAppMeta('menu_version', '0'); if (Number(stored) === MENU_VERSION) return; const items = loadMenuFromFolder(); await collection('menu_items').deleteMany({}); if (items.length) await collection('menu_items').insertMany(await Promise.all(items.map(async (item) => ({ id: await nextId('menu_items'), name: item.name, image: item.image, price: Number(item.price), category: item.category, available: true, noPlatformFee: Boolean(item.noPlatformFee) })))); await setAppMeta('menu_version', String(MENU_VERSION)); }

async function findUserByCredentials(identifier, password) { const parsed = normalizeAuthIdentifier(identifier); if (!String(password || '').trim()) return null; let query; if (parsed.kind === 'email') query = { $or: [{ email: parsed.value }, { usernameLower: parsed.value }] }; else if (parsed.kind === 'phone') query = { $or: [{ phone: parsed.value }, { usernameLower: parsed.value }] }; else if (parsed.kind === 'username') query = { usernameLower: parsed.value }; else return null; const user = await collection('users').findOne(query); return user && String(user.password).toLowerCase() === String(password).trim().toLowerCase() ? { id: user.id, username: user.username, password: user.password, role: user.role, email: user.email, phone: user.phone } : null; }
async function findUserByUsername(username) { return collection('users').findOne({ usernameLower: String(username || '').trim().toLowerCase() }, { projection: { password: 0 } }); }
async function findUserByEmail(email) { const value = normalizeAuthEmail(email); if (!value) return null; return collection('users').findOne({ $or: [{ email: value }, { usernameLower: value }] }, { projection: { password: 0 } }); }
async function findUserByPhone(phone) { const value = normalizeAuthPhone(phone); if (!value) return null; return collection('users').findOne({ $or: [{ phone: value }, { usernameLower: value }] }, { projection: { password: 0 } }); }
async function createUser(username, password, { email = null, phone = null, role = 'user' } = {}) { const user = { id: await nextId('users'), username, usernameLower: String(username).toLowerCase(), password, role, email: email || null, phone: phone || null, createdAt: new Date().toISOString() }; await collection('users').insertOne(user); return { id: user.id, username, role, email: user.email, phone: user.phone }; }
async function recordUserLogin(user, { identifier = '', ip = '', userAgent = '' } = {}) { if (!user?.id) return null; const record = { id: await nextId('login_history'), userId: user.id, username: user.username, identifier: String(identifier).slice(0, 191), ip: String(ip).slice(0, 64), userAgent: String(userAgent).slice(0, 255), loggedInAt: new Date().toISOString() }; await collection('login_history').insertOne(record); return { id: record.id, userId: user.id }; }
async function getMenuItems() { return collection('menu_items').find({ available: true }).sort({ category: 1, name: 1 }).project({ _id: 0, id: 1, name: 1, image: 1, price: 1, category: 1, noPlatformFee: 1 }).toArray(); }
async function getMenuItemByName(name) { const item = await collection('menu_items').findOne({ name, available: true }, { projection: { _id: 0, name: 1, price: 1, noPlatformFee: 1 } }); return item ? { ...item, price: Number(item.price), noPlatformFee: Boolean(item.noPlatformFee) } : null; }
async function getUserCart(userId) { const row = await collection('user_carts').findOne({ userId }); return row ? { cart: Array.isArray(row.cart) ? row.cart : [], orderDetails: row.orderDetails || null } : { cart: [], orderDetails: null }; }
async function saveUserCart(userId, cart, orderDetails) { if (userId) await collection('user_carts').updateOne({ userId }, { $set: { userId, cart: cart || [], orderDetails: orderDetails || null, updatedAt: new Date().toISOString() } }, { upsert: true }); }
async function clearUserCart(userId) { if (userId) await collection('user_carts').updateOne({ userId }, { $set: { cart: [], orderDetails: null, updatedAt: new Date().toISOString() } }, { upsert: true }); }
async function getSession(sid) { const row = await collection('sessions').findOne({ sid, expired: { $gte: Date.now() } }); if (!row) return null; try { return JSON.parse(row.sess); } catch (_) { return null; } }
async function setSession(sid, sess, maxAgeMs) { await collection('sessions').updateOne({ sid }, { $set: { sid, sess: JSON.stringify(sess), expired: Date.now() + (Number(maxAgeMs) || 86400000) } }, { upsert: true }); }
async function destroySession(sid) { await collection('sessions').deleteOne({ sid }); }
async function touchSession(sid, maxAgeMs) { await collection('sessions').updateOne({ sid }, { $set: { expired: Date.now() + (Number(maxAgeMs) || 86400000) } }); }
async function cleanupExpiredSessions() { if (database) await collection('sessions').deleteMany({ expired: { $lt: Date.now() } }); }

function mapOrder(order) { if (!order) return null; return { id: order.id, userId: order.userId, username: order.username, items: order.items || [], subtotal: Number(order.subtotal), coupon: Number(order.coupon), platformFee: Number(order.platformFee), total: Number(order.total), paymentMethod: order.paymentMethod, paymentMeta: order.paymentMeta || {}, serviceType: order.serviceType || 'dining', orderDetails: order.orderDetails || {}, status: order.status, placedAt: order.placedAt, completedAt: order.completedAt || null, updatedAt: order.updatedAt || order.placedAt || null, invoiceToken: order.invoiceToken || null }; }
async function createOrder(data) { const now = new Date().toISOString(); const order = { id: await nextId('orders'), userId: data.userId || null, username: data.username, items: data.items || [], subtotal: Number(data.subtotal || 0), coupon: Number(data.coupon || 0), platformFee: Number(data.platformFee || 0), total: Number(data.total || 0), paymentMethod: data.paymentMethod || 'card', paymentMeta: data.paymentMeta || {}, serviceType: data.serviceType || 'dining', orderDetails: data.orderDetails || {}, status: data.status || (data.paymentMethod === 'cod' ? 'confirmed' : 'paid'), placedAt: now, updatedAt: now, completedAt: null, invoiceToken: null }; await collection('orders').insertOne(order); return mapOrder(order); }
async function getOrderById(id) { return mapOrder(await collection('orders').findOne({ id: Number(id) || id })); }
async function getOrderByInvoiceToken(token) { return mapOrder(await collection('orders').findOne({ invoiceToken: String(token || '').trim() })); }
async function ensureInvoiceToken(orderId) { const order = await getOrderById(orderId); if (!order) return null; if (order.invoiceToken) return order; const token = `inv_${order.id}_${crypto.randomBytes(12).toString('hex')}`; await collection('orders').updateOne({ id: order.id }, { $set: { invoiceToken: token } }); return getOrderById(order.id); }
async function getOrdersByUserId(userId, options = {}) { const rows = await collection('orders').find({ userId: Number(userId) || userId }).sort({ placedAt: -1 }).toArray(); const status = String(options.status || '').toLowerCase(); const mapped = rows.map(mapOrder); if (!status || status === 'all') return mapped; if (status === 'active') return mapped.filter((o) => ['pending', 'confirmed', 'preparing', 'out_for_delivery', 'paid'].includes(o.status)); if (status === 'completed') return mapped.filter((o) => o.status === 'delivered'); if (status === 'cancelled') return mapped.filter((o) => o.status === 'cancelled'); return mapped.filter((o) => o.status === status); }
async function getAllOrders() { return (await collection('orders').find({}).sort({ placedAt: -1 }).toArray()).map(mapOrder); }
function isActiveOrder(order, hours = 24) { const age = Date.now() - new Date(order.placedAt).getTime(); return !Number.isNaN(age) && age <= hours * 3600000 && ['pending', 'confirmed', 'preparing', 'out_for_delivery', 'paid'].includes(String(order.status)); }
async function getActiveOrders(hours = 24) { return (await getAllOrders()).filter((order) => isActiveOrder(order, hours)); }
async function getOrdersArchiveByDate(hours = 24) { const archived = (await getAllOrders()).filter((order) => !isActiveOrder(order, hours)); const groups = new Map(); archived.forEach((order) => { const key = new Date(order.placedAt).toISOString().slice(0, 10); if (!groups.has(key)) groups.set(key, []); groups.get(key).push(order); }); return { hours, totalArchived: archived.length, dates: [...groups.keys()].sort((a, b) => b.localeCompare(a)).map((dateKey) => { const orders = groups.get(dateKey); return { dateKey, dateLabel: new Date(`${dateKey}T12:00:00`).toLocaleDateString('en-IN', { weekday: 'short', day: '2-digit', month: 'short', year: 'numeric' }), count: orders.length, revenue: orders.reduce((sum, order) => sum + order.total, 0), orders, details: orders.filter((order) => order.orderDetails?.fullName).map((order) => ({ orderId: order.id, username: order.username, serviceType: order.serviceType, orderDetails: order.orderDetails, items: order.items, total: order.total, paymentMethod: order.paymentMethod, status: order.status, placedAt: order.placedAt })) }; }) }; }
async function updateOrderStatus(orderId, status) { const allowed = ['pending', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'paid', 'cancelled']; if (!allowed.includes(status)) return null; const update = { status, updatedAt: new Date().toISOString() }; if (status === 'delivered' || status === 'cancelled') update.completedAt = update.updatedAt; const result = await collection('orders').updateOne({ id: Number(orderId) || orderId }, { $set: update }); return result.matchedCount ? getOrderById(orderId) : null; }

async function createContactMessage({ name, email, message }) { const record = { id: await nextId('contact_messages'), name, email, message, createdAt: new Date().toISOString() }; await collection('contact_messages').insertOne(record); return record; }
async function getAllContactMessages() { return collection('contact_messages').find({}).sort({ createdAt: -1 }).project({ _id: 0 }).toArray(); }
function mapCustomerMessage(row) { if (!row) return null; return { id: row.id, orderId: row.orderId, phone: row.phone, message: row.message, status: row.status, channel: row.channel, customerName: row.customerName || '', billTotal: row.billTotal != null ? Number(row.billTotal) : null, mediaType: row.mediaType || 'text', receiptCode: row.receiptCode || '', sendMethod: row.sendMethod || '', attemptCount: Number(row.attemptCount || 0), lastError: row.lastError || '', sentAt: row.sentAt || null, updatedAt: row.updatedAt || row.createdAt, createdAt: row.createdAt }; }
async function createCustomerMessage(data = {}) { const now = new Date().toISOString(); const existing = data.orderId ? await collection('customer_messages').findOne({ orderId: data.orderId, status: { $in: ['pending', 'queued', 'ready', 'failed'] } }, { sort: { createdAt: -1 } }) : null; const values = { phone: data.phone || '', message: data.message || '', status: data.status || 'pending', channel: data.channel || 'whatsapp', customerName: data.customerName || '', billTotal: data.billTotal != null ? Number(data.billTotal) : null, mediaType: data.mediaType || 'png', receiptCode: data.receiptCode || `CC-WA-${data.orderId || 'T'}-${Date.now().toString(36).toUpperCase()}`, sendMethod: data.sendMethod || '', lastError: data.lastError || null, updatedAt: now }; if (existing) { await collection('customer_messages').updateOne({ _id: existing._id }, { $set: values, $inc: { attemptCount: 1 } }); return mapCustomerMessage({ ...existing, ...values, attemptCount: Number(existing.attemptCount || 0) + 1 }); } const record = { id: await nextId('customer_messages'), orderId: data.orderId || null, ...values, attemptCount: 1, sentAt: null, createdAt: now }; await collection('customer_messages').insertOne(record); return mapCustomerMessage(record); }
async function getCustomerMessagesByCategory(search = '') { let all = (await collection('customer_messages').find({}).sort({ updatedAt: -1, createdAt: -1 }).toArray()).map(mapCustomerMessage); const q = String(search || '').trim().toLowerCase(); if (q) all = all.filter((m) => [m.phone, m.customerName, m.message, m.receiptCode, m.orderId, m.status, m.sendMethod].join(' ').toLowerCase().includes(q)); const sent = all.filter((m) => m.status === 'sent'); const failed = all.filter((m) => m.status === 'failed'); const pending = all.filter((m) => !['sent', 'failed'].includes(m.status)); return { all, sent, pending, failed, counts: { all: all.length, total: all.length, sent: sent.length, pending: pending.length, failed: failed.length } }; }
async function getPendingCustomerMessages() { return (await getCustomerMessagesByCategory()).pending; }
async function updateCustomerMessage(id, values) { const key = Number(id) || id; const result = await collection('customer_messages').updateOne({ id: key }, { $set: { ...values, updatedAt: new Date().toISOString() } }); return result.matchedCount ? mapCustomerMessage(await collection('customer_messages').findOne({ id: key })) : null; }
async function markCustomerMessageSent(id, opts = 'whatsapp') { const options = typeof opts === 'string' ? { channel: opts, sendMethod: 'whatsapp' } : opts || {}; return updateCustomerMessage(id, { status: 'sent', channel: options.channel || 'whatsapp', sendMethod: options.sendMethod || 'whatsapp', sentAt: new Date().toISOString(), lastError: null }); }
async function markCustomerMessageFailed(id, opts = 'whatsapp') { const options = typeof opts === 'string' ? { channel: opts } : opts || {}; return updateCustomerMessage(id, { status: 'failed', channel: options.channel || 'whatsapp', sendMethod: options.sendMethod || '', lastError: options.lastError || 'Send failed' }); }
async function getCustomerDetailsForAdmin({ activeOnly = true, hours = 24 } = {}) { const orders = activeOnly ? await getActiveOrders(hours) : await getAllOrders(); return orders.filter((order) => order.orderDetails?.fullName).map((order) => ({ orderId: order.id, username: order.username, serviceType: order.serviceType, orderDetails: order.orderDetails, items: order.items, total: order.total, paymentMethod: order.paymentMethod, status: order.status, placedAt: order.placedAt })); }
async function getAdminStats() { const [totalOrders, users, menuItems, revenue, activeOrders] = await Promise.all([collection('orders').countDocuments(), collection('users').countDocuments(), collection('menu_items').countDocuments({ available: true }), collection('orders').aggregate([{ $group: { _id: null, total: { $sum: '$total' } } }]).next(), collection('orders').countDocuments({ status: { $in: ['pending', 'confirmed', 'preparing'] } })]); return { totalOrders, totalRevenue: Number(revenue?.total || 0), activeOrders, totalUsers: users, menuItems }; }
async function getAppMeta(key, fallback = '') { const row = await collection('app_meta').findOne({ key }); return row ? row.value : fallback; }
async function setAppMeta(key, value) { await collection('app_meta').updateOne({ key }, { $set: { key, value: String(value ?? '') } }, { upsert: true }); }
async function getSmsSettings() { return { provider: await getAppMeta('sms_provider', 'whatsapp'), configured: true, easyMode: true, channel: 'whatsapp' }; }
async function saveSmsSettings(settings = {}) { for (const [key, value] of Object.entries(settings)) if (value != null) await setAppMeta(`sms_${key}`, value); return getSmsSettings(); }

module.exports = { engine: 'mongodb', hasMongoEnv, describeMongoEnv, formatMongoError, initMongo, normalizeAuthEmail, normalizeAuthPhone, normalizeAuthIdentifier, findUserByCredentials, findUserByUsername, findUserByEmail, findUserByPhone, createUser, recordUserLogin, getMenuItems, getMenuItemByName, getMenuCategories: (items) => getMenuCategories(items), getUserCart, saveUserCart, clearUserCart, getSession, setSession, destroySession, touchSession, cleanupExpiredSessions, createContactMessage, createOrder, getOrderById, getOrderByInvoiceToken, getOrdersByUserId, ensureInvoiceToken, getAllUsers: async () => collection('users').find({}).sort({ id: 1 }).project({ _id: 0, password: 0, usernameLower: 0 }).toArray(), getAllOrders, getActiveOrders, getOrdersArchiveByDate, updateOrderStatus, getAdminStats, getAllContactMessages, getCustomerDetailsForAdmin, getCustomerMessagesByCategory, getPendingCustomerMessages, markCustomerMessageSent, markCustomerMessageFailed, createCustomerMessage, getSmsSettings, saveSmsSettings, getAppMeta, setAppMeta };